# Generated by Django 2.0.3 on 2018-03-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=120)),
                ('chi_name', models.CharField(blank=True, max_length=120)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
