# Generated by Django 2.0.3 on 2018-03-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newobj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name': 'amenity', 'verbose_name_plural': 'amenities'},
        ),
        migrations.AlterField(
            model_name='amenity',
            name='chi_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Chinese Name'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='eng_name',
            field=models.CharField(max_length=120, verbose_name='English Name'),
        ),
    ]
